---
- name: Edit Demo Credential
  tower_credential:
    name: demo
    kind: ssh
    organization: Default
    password: "{{ password }}"
    state: present
    username: admin
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"
    vault_password: "{{ password }}"

- name: Add NXOS Credentials
  tower_credential:
    name: nxos
    kind: net
    organization: Default
    username: cisco
    password: "{{ password }}"
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: Add network credentials
  tower_credential:
    name: network
    kind: net
    organization: Default
    username: admin
    password: "{{ password1 }}"
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"
