---
- name: create the sales demo admin project
  tower_project:
    config_file: ~/.tower_cli.cfg
    name: Ansible NXOS
    description: Networking playgooks
    organization: Ansible Sales Demo
    scm_type: git
    scm_url: https://github.com/jmcleroy/jpoc
    scm_branch: master
    scm_clean: no
    scm_delete_on_update: no
    scm_update_on_launch: yes
    state: present

- name: create all sales demo job templates
  shell: >
    tower-cli job_template create
    --name "{{ item.name }}"
    --description "{{ item.description }}"
    --job-type "{{ item.job_type }}"
    --project "{{ item.project }}"
    --playbook "{{ item.playbook }}"
    --machine-credential "{{ item.machine_credential }}"
    --network-credential "{{ item.network_credential }}"
    --limit "{{ item.limit | default('') }}"
    --extra-vars "{{ item.extra_vars | default('foo: bar') | from_yaml | to_yaml }}"
    --ask-inventory-on-launch "{{ item.ask_inventory_on_launch | default('no') | bool }}"
    --ask-job-type-on-launch "{{ item.ask_job_type_on_launch | default('no') | bool }}"
  with_items: "{{ sales_demo_job_templates }}"