---
- name: Create NXOS backup job template
  tower_job_template:
    name: "nxos backup"
    description: "backup nxos"
    job_type: "run"
    inventory: "NXOS"
    project: "NXOS"
    playbook: "nxos_backup.yml"
    machine_credential: "machine"
    network_credential: "nxos"
    state: present
    tower_verify_ssl: false
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"
