---
- name: Edit Demo Credential
  tower_credential:
    name: Demo Credential
    kind: ssh
    organization: Default
    password: "{{ password }}"
    state: present
    username: admin
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"
    vault_password: "{{ password }}"

- name: Add NXOS Credentials
  tower_credential:
    name: nxos
    kind: net
    organization: Default
    username: cisco
    password: "{{ password }}"
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: Add network credentials
  tower_credential:
    name: network
    kind: net
    organization: Default
    username: admin
    password: "{{ password1 }}"
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: create the sales demo nxos project
  tower_project:
    name: Ansible NXOS
    description: Networking playbooks
    scm_type: git
    scm_url: https://github.com/jmcleroy/jpoc
    scm_clean: no
    scm_delete_on_update: no
    scm_update_on_launch: yes
    state: present
    organization: Default
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: create the sales demo f5 project
  tower_project:
    name: Ansible F5
    description: Networking playbooks
    scm_type: git
    scm_url: https://github.com/jmcleroy/f5bigip
    scm_clean: no
    scm_delete_on_update: no
    scm_update_on_launch: yes
    organization: Default
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: Create NXOS backup
  tower_job_template:
    name: nxos_backup
    job_type: run
    inventory: NXOS
    project: Ansible NXOS
    playbook: nxos_backup.yml
    machine_credential: nxos
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"