---
sales_demo_projects:
  - name: Ansible NXOS
    scm_url: https://github.com/jmcleroy/jpoc
    team_roles:
      - name: admin
        type: update
      - name: admin
        type: use
      - name: admin
        type: admin

sales_demo_job_templates:
  - name: NXOS Backup Configuration
    description: "Shut down and delete a user's demo instances in AWS by Tower username"
    job_type: run
    project: Ansible NXOS
    playbook: nxos_backup.yml
    ask_inventory: yes
    machine_credential: Demo Credentials
    network_credential: Network
    extra_vars:
    team_roles:
      - name: admin
        type: execute
      - name: admin
        type: admin