---
sales_demo_job_templates:
  - name: NXOS Backup Configuration
    description: "Shut down and delete a user's demo instances in AWS by Tower username"
    job_type: run
    project: 'Ansible NXOS'
    playbook: nxos_backup.yml
    ask_inventory: no
    machine_credential: Demo 'Credentials'
    network_credential: nxos
    inventory: NXOS