---
- name: create the sales demo nxos project
  tower_project:
    name: NXOS
    description: Networking playbooks
    scm_type: git
    scm_url: https://github.com/jmcleroy/jpoc
    scm_clean: no
    scm_delete_on_update: no
    scm_update_on_launch: yes
    state: present
    organization: Default
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"

- name: create the sales demo f5 project
  tower_project:
    name: F5
    description: Networking playbooks
    scm_type: git
    scm_url: https://github.com/jmcleroy/f5bigip
    scm_clean: no
    scm_delete_on_update: no
    scm_update_on_launch: yes
    organization: Default
    state: present
    tower_host: "{{ host }}"
    tower_username: "{{ username }}"
    tower_password: "{{ password }}"
